### PR TITLE
Fix formula constant and add constant values to calculator result

### LINKED ISSUE #71: Fix national grid gross loss used in calculation
In the EmissionsCalculator.vue the grid gross loss for national is hard coded.  This needs to be updated to the 2019 value.  We also need to have a better way of updating this value when it changes.

### LINKED ISSUE #81: Fix formula constants used in the calculation

### PR DESCRIPTION
**Pull request by ntknguyen**
closes #71 and #81

### CODE REVIEW

File: app/src/components/CalculatorResults.vue [hunk 1]
```diff
@@ -120,10 +126,10 @@
       </div>
       <i18n path="seedlingParagraph" tag="p">
         <template #numSeedlings>
-          <span id="no-of-tree-seedlings"></span>
+          <span id="nat-no-of-tree-seedlings"></span>
```
Comment (j-tafoya) [inline app/src/components/CalculatorResults.vue]: Actually, I think you can remove this nat-

I fixed it in my branch

**Review by j-tafoya — APPROVED** [review]
Looks good to me, just remove the nat- from the calculator results seedlings template

**Review by j-tafoya — APPROVED** [review]
perfect!
