### PR TITLE
reset previous options when select egrid-subregions

### LINKED ISSUE #89: Emissions Rate bar charts broken when changing to "Back to all regions" and selected eGRID Subregions from the left side panel.

### LINKED ISSUE #90: Maps disappear when changing to "Back to all regions and selected eGRID Subregions from the left side panel

### PR DESCRIPTION
**Pull request by ntknguyen**
reset previous selection when selecting "eGRID subregions" from list.  Changes applied to two files: main.js and SubregionSelection.vue.  Preview page: https://test-power-profiler-fix-egrid-selection.app.cloud.gov/#/

### CODE REVIEW

File: app/src/main.js [hunk 1]
```diff
@@ -27,14 +27,22 @@ var vm = new Vue({
 });
 
 vm.$on("subregionSelected", function(d) {
+  if (d === "All") {
+    $(".map").css({ fill: "" });
+    this.$children[0].$children[4].$children[0].selectedRegion = {};
```
Comment (j-tafoya) [inline app/src/main.js:32]: I think there's a way we can avoid doing this children.children stuff. I'm working on figuring that out.

File: app/src/main.js [hunk 2]
```diff
@@ -27,14 +27,22 @@ var vm = new Vue({
...
+    this.$children[0].$children[4].selectedRegion = {};
+    this.$root.showMain = true;
+    this.$root.selectedSubregion = false;
```
Comment (j-tafoya) [inline app/src/main.js:35]: You don't need to do lines 34 and 35. Instead of 35, you should do `selectedSubregion.update({})`

**Review by maheese — APPROVED** [review]
